extends Node3D

@export var terrain_path: NodePath = NodePath("Terreno_Finca")
@export var collision_root_name: String = "GeneratedCollisions"
@export_flags_3d_physics var world_collision_layer: int = 2
@export_flags_3d_physics var world_collision_mask: int = 5
@export var exact_mesh_names: PackedStringArray = [
	"Terrain_Main",
	"Mtn_Main",
	"Bridge_01",
	"Bridge_Ramp_South",
	"Lake_Bed",
	"Lake_Shore_Slope",
	"River_Bed",
	"Dock_01",
	"Corral_01",
	"Barn_01",
	"Cave_Main",
	"Cave_Mouth_Visible",
	"Cave_Lip_Left",
	"Cave_Lip_Right",
	"Cave_Lip_Top",
	"Borde_Alto_Norte",
]
@export var mesh_name_prefixes: PackedStringArray = [
	"Fence_Plain_",
	"Rock_M",
	"Rock_L",
	"River_Rock_",
	"Cave_Rock_",
	"TreeTall",
	"Log_",
]
@export var mesh_name_suffixes: PackedStringArray = [
	"_Trunk",
]
## Mesh names (or prefixes) baked into the GLB that must be hidden at runtime.
@export var hide_mesh_names: PackedStringArray = []
## The visible water is generated by Godot RiverSystem/LakeSystem. Baked GLB
## water overrides stay empty so old lake/river meshes cannot reappear.
@export var water_overrides: Dictionary = {}


func _ready() -> void:
	call_deferred("build_basic_collisions")


func build_basic_collisions() -> void:
	if has_node(collision_root_name):
		return

	var terrain := get_node_or_null(terrain_path)
	if terrain == null:
		push_warning("Terreno_Finca not found for collision generation.")
		return

	_hide_baked_meshes(terrain)
	_apply_water_materials(terrain)

	var collision_root := Node3D.new()
	collision_root.name = collision_root_name
	add_child(collision_root)

	var mesh_nodes: Array[MeshInstance3D] = []
	_collect_collision_meshes(terrain, mesh_nodes)

	for mesh_node in mesh_nodes:
		var shape := mesh_node.mesh.create_trimesh_shape()
		if shape == null:
			push_warning("Could not create trimesh collision for: %s" % mesh_node.name)
			continue

		var body := StaticBody3D.new()
		body.name = "%s_Collision" % mesh_node.name
		body.collision_layer = world_collision_layer
		body.collision_mask = world_collision_mask
		collision_root.add_child(body)
		body.global_transform = mesh_node.global_transform

		var collision_shape := CollisionShape3D.new()
		collision_shape.name = "CollisionShape3D"
		collision_shape.shape = shape
		body.add_child(collision_shape)


func _hide_baked_meshes(root: Node) -> void:
	if root is VisualInstance3D:
		var node_name := str(root.name)
		for hidden in hide_mesh_names:
			if node_name == hidden or node_name.begins_with(hidden) or node_name.ends_with(hidden):
				(root as Node3D).visible = false
				break
	for child in root.get_children():
		_hide_baked_meshes(child)


func _apply_water_materials(root: Node) -> void:
	if root is MeshInstance3D:
		var path: String = str(water_overrides.get(str(root.name), ""))
		if path != "":
			var mat := load(path)
			if mat != null:
				(root as MeshInstance3D).material_override = mat
	for child in root.get_children():
		_apply_water_materials(child)


func _collect_collision_meshes(root: Node, out: Array[MeshInstance3D]) -> void:
	if root is MeshInstance3D:
		var mesh_node := root as MeshInstance3D
		if mesh_node.mesh != null and _should_collide(mesh_node.name):
			out.append(mesh_node)

	for child in root.get_children():
		_collect_collision_meshes(child, out)


func _should_collide(mesh_name: StringName) -> bool:
	var name := str(mesh_name)
	if exact_mesh_names.has(name):
		return true

	for prefix in mesh_name_prefixes:
		if name.begins_with(prefix):
			return true

	for suffix in mesh_name_suffixes:
		if name.ends_with(suffix):
			return true

	return false
